name: retrokit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
 
  google_fonts: 3.0.1
  spring: 2.0.2
  flutter_blue: 0.8.0
  flutter_bounce: 1.1.0
  getwidget: 3.0.1
  flutter_reactive_ble: ^5.0.3
  location_permissions: ^4.0.1
  bluetooth_enable_fork: 0.1.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/images/Retrokit Vector.png
    - assets/images/Retrokit Vector logo.png
  uses-material-design: true

